### ISSUE TITLE
Calling `auth/refresh` twice triggers `MethodNotAllowedHttpException`

### ISSUE THREAD

**Issue by YassineGherbi** [MuhoX/tweenstalent-api#6]
**Reproduce:** 
1. Call `auth/login`
2. Call `auth/refresh` twice 
3. `MethodNotAllowedHttpException`

**Comment by MuhoX** [comment]
This is not a bug, when you do refresh, you get a new token. You probably did not enter the new code to authorise so it threw an exception.
