### ISSUE TITLE
Registering with different field

### ISSUE THREAD

**Issue by YassineGherbi** [MuhoX/tweenstalent-api#8]
Right now the users are signing up with this form: 

![image](https://user-images.githubusercontent.com/15906337/41312441-5c827904-6e87-11e8-93b0-d9dfb67232f5.png)

The problem is that a POST request to `/user` required a `firstName, lastnamePrefix and lastName`.

How should this be handled?

**Comment by MuhoX** [comment]
I made the last name prefix nullable.
